{{- if (not .Values.persistence.existingClaim) }}
{{- if or ( .Values.persistence.enabled )  ( .Values.global.persistence.enabled ) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ template "mysqlVolumeSize" . }}
  storageClassName: {{ template "mysqlVolumeStorageClass" . }}
{{- end }}
{{- end }}
